// <auto-generated>
internal static class BuildInfo
{
    public const string GitTag = "__GIT_TAG__";
    public const string GitVersion = "__GIT_VERSION__";
    public const string GitCommitHash = "__GIT_COMMIT__";
}